In [ ]:
# y2_np                                                  out2_np
array([-6614.237], dtype=float32) 

In [1]:
import torch

# 假设这是你的 Tensor，且它在计算图中
t = torch.rand((3, 3, 3, 3), dtype=torch.float32, requires_grad=True)  # 示例 Tensor，跟踪梯度

# 将 Tensor 从计算图中分离，然后转换为 NumPy 数组
P = t.detach().numpy()

# 如果 Tensor 在 GPU 上，先将其移动到 CPU，再转换为 NumPy 数组
# P = t.detach().cpu().numpy()

# 打印 NumPy 数组 P
print(P)  # 输出类似于 array([...], dtype=float32)



[[[[0.52306664 0.73206496 0.394374  ]
   [0.03842193 0.2933523  0.6611045 ]
   [0.65825605 0.8242239  0.69264567]]

  [[0.82936543 0.48637414 0.2719661 ]
   [0.65146726 0.48275805 0.86533463]
   [0.03820598 0.7856822  0.75778866]]

  [[0.29765052 0.31160194 0.17574775]
   [0.6989369  0.4847893  0.672575  ]
   [0.26014537 0.9491436  0.74866265]]]


 [[[0.726058   0.16202646 0.03133106]
   [0.55482155 0.8962566  0.46777207]
   [0.2802856  0.8963872  0.16254485]]

  [[0.54452085 0.40977824 0.41512316]
   [0.86993384 0.4854201  0.2704751 ]
   [0.7960337  0.40097457 0.635815  ]]

  [[0.12490445 0.49223125 0.27802372]
   [0.16643703 0.74736005 0.44139737]
   [0.49016744 0.21272314 0.30674595]]]


 [[[0.11086047 0.92905456 0.5477746 ]
   [0.68883723 0.31463152 0.6004455 ]
   [0.43416685 0.2985447  0.24744588]]

  [[0.84950846 0.13948357 0.38486266]
   [0.40065485 0.17458963 0.13208735]
   [0.6466715  0.62996775 0.8721378 ]]

  [[0.12601542 0.51273406 0.95350295]
   [0.2894531  0.8085395  0.54