In [2]:
import torch

In [3]:
torch.arange(0, 10, 2)


tensor([0, 2, 4, 6, 8])

In [12]:
x = torch.arange(0, 10).unsqueeze(0)
print(x.size(1))

TypeError: 'torch.Size' object is not callable

In [22]:
import torch.nn.functional as F
logits = torch.tensor([[0.4265, 0.2857],
        [0.3019, 0.7257]])
pred = F.softmax(logits, dim=-1)
pred1 = F.log_softmax(logits, dim=1)
print(logits)
print(pred)
print(pred1)


tensor([[0.4265, 0.2857],
        [0.3019, 0.7257]])
tensor([[0.5351, 0.4649],
        [0.3956, 0.6044]])
tensor([[-0.6252, -0.7660],
        [-0.9273, -0.5035]])


In [23]:

a=torch.tensor([[[5,5,5,5], [6,6,6,6], [7,7,7,7]], [[1,1,1,1],[2,2,2,2],[3,3,3,3]]])
print(a)
print(a.size())
print("#############################################3")
mask = torch.ByteTensor([[[1],[1],[0]],[[0],[1],[1]]])
print(mask.size())
b = a.masked_fill(mask, value=torch.tensor(-1e9))
print(b)
print(b.size())

tensor([[[5, 5, 5, 5],
         [6, 6, 6, 6],
         [7, 7, 7, 7]],

        [[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]]])
torch.Size([2, 3, 4])
#############################################3
torch.Size([2, 3, 1])


RuntimeError: masked_fill_ only supports boolean masks, but got mask with dtype unsigned char

In [25]:
def subsequent_mask(size):
    "Mask out subsequent positions"
    attention_shape = (1, size, size)
    subsequent_mask = torch.triu(torch.ones(attention_shape), diagonal=1).type(torch.uint8)
    # torch.triu
    return subsequent_mask == 0

print(subsequent_mask(10))


tensor([[[1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
         [1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
         [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
         [1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
         [1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]], dtype=torch.uint8)
